name: Bug report
description: Report a reproducible problem in Civic Stack
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: Clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant environment details.
      placeholder: |
        OS:
        Node/Bun version:
        Browser (if applicable):
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Add any relevant logs or screenshots.
    validations:
      required: false
